[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
numReplicas = 1
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
