[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["apps/web/**"]

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/health"
healthcheckTimeout = 100
numReplicas = 1
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
